# for Database
MYSQL_USERNAME: root
MYSQL_PASSWORD: 1234
MYSQL_HOST: 127.0.0.1
MYSQL_PORT: 3306
#MYSQL_PORT: 3307
MYSQL_DATABASE: mipueblo

# for Server Config
CONTAINER_PORT: 8085
ACTIVE_PROFILE: dev

# for Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: <email here>
EMAIL_PASSWORD: <pass here>
VERIFY_EMAIL_HOST: http://localhost:${CONTAINER_PORT}

# for UI Config
UI_APP_URL: http://localhost:4200

JWT_SECRET: asecret
